DROP TABLE IF EXISTS authors;

CREATE TABLE authors (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL
);

INSERT INTO authors (first_name, last_name) VALUES
  ('Gracjan', 'Grala'),
  ('Adam', 'Krzanowski');

-- DATA FOR NOT ADVANCED USER DEFINITION OF ATTRIUBTE SUMMARY AND MEMBERSHIP POINTS
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (1, 'PRICE', 'TRIANGULAR', 'cheap', 0, 60000, 120000, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (2, 'PRICE', 'TRIANGULAR', 'low', 80000, 130000, 180000, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (3, 'PRICE', 'TRIANGULAR', 'normal', 160000, 257500, 355000, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (4, 'PRICE', 'TRIANGULAR', 'high', 275000, 537500, 800000, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (5, 'PRICE', 'TRIANGULAR', 'expensive', 750000, 1000000, 7700000, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (6, 'BEDROOM', 'TRIANGULAR', 'lack', 0, 0, 0, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (7, 'BEDROOM', 'TRIANGULAR', 'little', 0, 1.5, 3, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (8, 'BEDROOM', 'TRIANGULAR', 'usual', 1, 2.5, 4, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (9, 'BEDROOM', 'TRIANGULAR', 'a lot of', 3, 8, 13, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (10, 'BEDROOM', 'TRIANGULAR', 'hotel', 9, 21, 33, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (11, 'BATHROOM', 'TRIANGULAR', 'lack', 0, 0, 0, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (12, 'BATHROOM', 'TRIANGULAR', 'poor', 0, 1, 2, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (13, 'BATHROOM', 'TRIANGULAR', 'usual', 1, 2, 3, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (14, 'BATHROOM', 'TRIANGULAR', 'many of', 2.5, 3.5, 4.5, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (15, 'BATHROOM', 'TRIANGULAR', 'richly', 4, 6, 8, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (16, 'RESIDENTIAL_AREA', 'TRAPEZOIDAL', 'cramped', 0, 200, 600, 800);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (17, 'RESIDENTIAL_AREA', 'TRAPEZOIDAL', 'rather tight', 600, 900, 1500, 1800);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (18, 'RESIDENTIAL_AREA', 'TRAPEZOIDAL', 'average-size', 1550, 2112.5, 3237.5, 3800);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (19, 'RESIDENTIAL_AREA', 'TRAPEZOIDAL', 'quite spacious', 3200, 4500, 7100, 8400);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (20, 'RESIDENTIAL_AREA', 'TRAPEZOIDAL', 'extremely spacious', 7500, 9010, 12030, 13540);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (21, 'GARDEN_AREA', 'TRAPEZOIDAL', 'cramped', 0, 1750, 5250, 7000);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (22, 'GARDEN_AREA', 'TRAPEZOIDAL', 'rather tight', 5000, 7500, 12500, 15000);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (23, 'GARDEN_AREA', 'TRAPEZOIDAL', 'average-size', 10000, 16250, 28750, 35000);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (24, 'GARDEN_AREA', 'TRAPEZOIDAL', 'quite spacious', 19000, 36750, 72250, 90000);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (25, 'GARDEN_AREA', 'TRAPEZOIDAL', 'extremely spacious', 75000, 94089.75, 132269.25, 151359);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (26, 'FLOOR', 'TRAPEZOIDAL', 'one floor', 0, 0.5, 1.5, 2);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (27, 'FLOOR', 'TRAPEZOIDAL', 'many floors', 1.2, 1.775, 2.925, 3.5);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (28, 'STATE', 'TRIANGULAR', 'ruin', 0, 1, 2, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (29, 'STATE', 'TRIANGULAR', 'neglected', 1, 2, 3, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (30, 'STATE', 'TRIANGULAR', 'normal', 2, 3, 4, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (31, 'STATE', 'TRIANGULAR', 'well-kept', 3, 4, 5, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (32, 'STATE', 'TRIANGULAR', 'perfect', 4, 5, 6, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (33, 'ATTIC_AREA', 'TRAPEZOIDAL', 'cramped', 0, 125, 375, 500);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (34, 'ATTIC_AREA', 'TRAPEZOIDAL', 'rather tight', 400, 600, 1000, 1200);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (35, 'ATTIC_AREA', 'TRAPEZOIDAL', 'average-size', 900, 1537.5, 2812.5, 3450);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (36, 'ATTIC_AREA', 'TRAPEZOIDAL', 'quite spacious', 3000, 3562.5, 4687.5, 5250);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (37, 'ATTIC_AREA', 'TRAPEZOIDAL', 'extremely spacious', 4600, 5802.5, 8207.5, 9410);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (38, 'BASEMENT_AREA', 'TRAPEZOIDAL', 'lack', 0, 0, 0, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (39, 'BASEMENT_AREA', 'TRAPEZOIDAL', 'rather tight', 0, 275, 825, 1100);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (40, 'BASEMENT_AREA', 'TRAPEZOIDAL', 'average-size', 1000, 1350, 2050, 2400);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (41, 'BASEMENT_AREA', 'TRAPEZOIDAL', 'quite spacious', 2300, 2525, 2975, 3200);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (42, 'BASEMENT_AREA', 'TRAPEZOIDAL', 'extremely spacious', 3000, 3455, 4365, 4820);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (43, 'BUILDING_AGE', 'TRIANGULAR', 'historical', 80, 100, 120, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (44, 'BUILDING_AGE', 'TRIANGULAR', 'old', 50, 67.5, 85, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (45, 'BUILDING_AGE', 'TRIANGULAR', 'common', 20, 40, 60, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (46, 'BUILDING_AGE', 'TRIANGULAR', 'new', 0, 12.5, 25, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (47, 'RENOVATION_AGE', 'TRIANGULAR', 'not renovated or renovated a very long time ago', 32, 59, 86, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (48, 'RENOVATION_AGE', 'TRIANGULAR', 'long time renovated', 16, 28, 40, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (49, 'RENOVATION_AGE', 'TRIANGULAR', 'recently renovated', 5, 12.5, 20, 0);
INSERT INTO PUBLIC.ATTRIBUTE_SUMMARY (ID_ATTRIBUTE_SUMMARY, ATTRIBUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (50, 'RENOVATION_AGE', 'TRIANGULAR', 'newly renovated', 0, 5, 10, 0);