INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (false, 'TRIANGULAR', 'none', 0, 0, 0, 0);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (false, 'TRIANGULAR', 'about a quarter', 0.2, 0.25, 0.3, 0);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (false, 'TRIANGULAR', 'almost none', 0.01, 0.05, 0.1, 0);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (false, 'TRAPEZOIDAL', 'almost all', 0.85, 0.9, 0.95, 0.99);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (false, 'TRAPEZOIDAL', 'most', 0.5, 0.6, 0.7, 0.8);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (true, 'TRIANGULAR', 'about 1000', 850, 1000, 1150, 0);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (true, 'TRIANGULAR', 'over 2000', 2000, 21000, 21000, 0);
INSERT INTO PUBLIC.QUANTIFIERS (IS_ABSOLUTE, MEMBERSHIP_TYPE, NAME, POINT_A, POINT_B, POINT_C, POINT_D) VALUES (true, 'TRIANGULAR', 'below 500', 0, 1, 500, 0);